import {
  Target,
  RotateCw,
  Zap,
  Hammer,
  Keyboard,
  Calculator,
  Palette,
  ScanEye,
  Music,
  GripVertical,
  Pencil,
  Crosshair,
  LayoutGrid,
  Hash,
  ParkingSquare,
  BarChartHorizontal,
  Puzzle,
  Brush,
  LucideIcon,
} from 'lucide-react'

export const GAME_ICONS: Record<string, LucideIcon> = {
  emoji_keypad: Target,
  image_rotate: RotateCw,
  reaction_time: Zap,
  whack_a_mole: Hammer,
  typing_speed: Keyboard,
  mental_math: Calculator,
  color_match: Palette,
  visual_diff: ScanEye,
  audio_pattern: Music,
  drag_sort: GripVertical,
  follow_me: Pencil,
  duck_shoot: Crosshair,
  memory_cards: LayoutGrid,
  number_chain: Hash,
  gridlock: ParkingSquare,
  reaction_bars: BarChartHorizontal,
  image_puzzle: Puzzle,
  draw_me: Brush,
}
